# Generated by Django 4.1.1 on 2022-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image",
        ),
    ]
