# Generated by Django 4.1.1 on 2022-09-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_blogpost_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="downvote",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="upvote",
        ),
    ]
