# Generated by Django 4.1.1 on 2022-09-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_blogpost_downvote_remove_blogpost_upvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="tag",
        ),
    ]
