# Generated by Django 4.1.1 on 2022-09-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_blogpost_tag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
