# Generated by Django 4.1.1 on 2022-09-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
