# Generated by Django 4.1.1 on 2022-09-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_downvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upvote",
            name="post_id",
        ),
        migrations.RemoveField(
            model_name="upvote",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Downvote",
        ),
        migrations.DeleteModel(
            name="Upvote",
        ),
    ]
