# Generated by Django 4.1.1 on 2022-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_vote_remove_upvote_post_remove_upvote_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.TextField(
                choices=[("upvote", "upvote"), ("downvote", "downvote")]
            ),
        ),
    ]
