# Generated by Django 4.1.1 on 2022-09-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0018_alter_vote_vote_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("upvote", "upvote"), ("downvote", "downvote")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="ReplyOfComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.comments"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
